# Generated by Django 4.2.13 on 2024-05-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_created_at_store_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
