# Generated by Django 4.2.13 on 2024-05-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
