# Generated by Django 4.2.13 on 2024-05-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_discountimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discounts',
        ),
    ]
